version: 2
jobs:
  frontend_test:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      - run: cd client
      - run: npm install
      - run: npm run test
  backend_test:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      - run: cd server
      - run: npm install
      - run: npm run test
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - frontend_test
      - backend_test
