version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run: cd server && yarn install
      - run: cd server && yarn install
  test:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run: cd client && yarn test
      - run: cd server && yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
