version: 2
jobs:
  frontend_test:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run: cd client && yarn install
      - run: yarn test
  backend_test:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run: cd server && yarn install
      - run: yarn test
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - frontend_test
      - backend_test
